#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV
bspc monitor eDP-1-1 -d I II III IV
bspc monitor DP-1 -d V VI VII VIII
bspc monitor DP-2 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config paddingless_monocle	 true
# bspc config automatic_scheme	spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=offa

#Mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier	super


picom  -b --config ~/.config/picom/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrdb ~/.config/X11/Xresources & 
setxkbmap -layout pl &
flashfocus
nm-applet &
greenclip daemon &
~/.config/i3/wallpaper.sh &
~/.config/polybar/polybar.sh &
